monitors:
- type: signalfx-forwarder
  listenAddress: 0.0.0.0:9080
  extraSpanTags:
    environment: test_app_JMR1 

- type: kubernetes-events
  whitelistedEvents:
   - reason: Killing
     involvedObjectKind: Pod
   - reason: Created
     involvedObjectKind: Pod
   - reason: ScalingReplicaSet
     involvedObjectKind: Deployment
   - reason: SuccessfulCreate
     involvedObjectKind: ReplicaSet
   - reason: Scheduled
     involvedObjectKind: Pod
   - reason: Started
     involvedObjectKind: Pod
   - reason: Pulled
     involvedObjectKind: Pod


# SBmpkOm8Vquqspus58TrnQ
