apiVersion: enterprise.splunk.com/v1beta1
# kind: SearchHeadCluster
kind: Standalone
metadata:
  name: itsi
  # name: dfsexample
  # finalizers:
  # - enterprise.splunk.com/delete-pvc
spec:
  sparkRef:
    name: example
  sparkImage: splunk/spark:edge
  # clusterMasterRef:
  #   name: cm
  # licenseMasterRef:
  #   name: example
  varVolumeStorageConfig:
    ephemeralStorage: true
  etcVolumeStorageConfig:
    storageCapacity: "20Gi"
  # varStorage: "10Gi"
  # replicas: 3
  # ephemeralStorage: true
  volumes:
    - name: apps
      configMap:
        name: splunk-apps
  defaults: |-
    splunk:
      apps_location:
        - "/mnt/apps/eksdemo.tgz"
        - "http://10.0.0.190:9000/apps/splunk-it-service-intelligence_471.tar.gz"


# have to use sparkimage variable to install java -- that's lame!
# splunk apply shcluster-bundle --answer-yes -target https://splunk-itsi-search-head-service:8089 -auth admin:VBu6U7pUbx2DBoWkbUUGD36h
# entity import 
# index=_internal earliest=-10m 
# | stats count by host 
# | eval splunk_role=case(like('host',"%cluster%"),"indexer_cluster_master", like('host',"%monitoring%"), "mgmt_console",like('host',"%hwf%"), "heavy_forwarder", like('host',"%idxc%"), "indexer", like('host',"%itsi-search-head%"), "search_head_cluster",true(),"search_head") |fields - count